import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage()
p.on('pageerror', e => console.log('PAGEERR', e.message))
p.on('console', m => { if (m.type() === 'error') console.log('ERR', m.text()) })
await p.goto('http://localhost:7851/')
await p.waitForTimeout(800)
const techNode = p.locator('.zm-node:has-text("技术栈")').first()
await techNode.click()
await p.waitForTimeout(200)
const before = await p.locator('.zm-node').count()
console.log('BEFORE_TAB', before)
await p.keyboard.press('Tab')
await p.waitForTimeout(300)
const afterTab = await p.locator('.zm-node').count()
console.log('AFTER_TAB', afterTab)
// What's focused now?
const focus = await p.evaluate(() => document.activeElement?.tagName + ' ' + document.activeElement?.className)
console.log('FOCUS_AFTER_TAB', focus)
await p.keyboard.type('Foo')
await p.waitForTimeout(200)
const focus2 = await p.evaluate(() => document.activeElement?.tagName + ' ' + document.activeElement?.className)
console.log('FOCUS_AFTER_TYPE', focus2)
const value = await p.evaluate(() => document.activeElement?.value)
console.log('ACTIVE_VALUE', value)
await p.keyboard.press('Enter')
await p.waitForTimeout(300)
const afterEnter = await p.locator('.zm-node').count()
console.log('AFTER_ENTER', afterEnter)
await b.close()
